Quality_Control/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('test/', include('test_1.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import AccountCreateView, AccountUpdateView, AccountDeleteView, AccountDetailView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
]

test_1/urls.py
from django.urls import path
from . import views

from test_1.views import MainView

app_name = 'test_1'

urlpatterns = [
    path('main/', MainView.as_view(), name='main'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>
    {% include 'body.html' %}
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="Quality_Control_footer">
    <div class="Quality_Control_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스소개</span>
    </div>
    <div style="margin-top: 1rem">
        <h6 class="Quality_Control_footer_logo">
            Quality Control Software
        </h6>
    </div>
</div>

templates/head.html
{%  load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, shrink-to-fit=no">
  <title>Quality_Control_Software_Project</title>
{#    Bootstrap link#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
{#    Google Font Link#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
{#    Google Matrial Icons#}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
{#    Default CSS Link#}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

templates/header.html
<div class="Quality_Control_header">
    <div>
        <h1 class="Quality_Control_logo">
            Quality Control Software Project
        </h1>
    </div>
    <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">Navbar</a>
        {% if not user.is_authenticated %}
            <a href="{%  url 'accountapp:login' %}?next={{ request.path }}" class="Quality_Control_header">
                <span>login</span>
            </a>
            <a href="{%  url 'accountapp:create' %}?next={{ request.path }}" class="Quality_Control_header">
                <span>SignUp</span>
            </a>
            {%  else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="Quality_Control_header">
                <span>MyPage</span>
            </a>
            <a href="{%  url 'accountapp:logout' %}?next={{ request.path}}"
            style="border-color: black">
                <span>logout</span>
            </a>
        {% endif %}
        <a class="navbar-brand">MyPage</a>
        <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>

templates/menu.html
<nav id="navbar-example3" class="navbar navbar-light bg-light flex-column align-items-stretch p-3"
        >
  <a class="navbar-brand" href="#">OQC Part</a>
  <nav class="nav nav-pills flex-column">
    <a class="nav-link" href="#item-1">Instrument</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ms-3 my-1" href="#item-1-1">Starlet</a>
      <a class="nav-link ms-3 my-1" href="#item-1-2">Nimbus</a>
      <a class="nav-link ms-3 my-1" href="#item-1-2">CFX96</a>
      <a class="nav-link ms-3 my-1" href="#item-1-2">Aios</a>
    </nav>
    <a class="nav-link" href="#item-2">Setting</a>
    <a class="nav-link" href="#item-3">계측기</a>
    <nav class="nav nav-pills flex-column">
      <a class="nav-link ms-3 my-1" href="#item-3-1">계측기1</a>
      <a class="nav-link ms-3 my-1" href="#item-3-2">계측기2</a>
    </nav>
  </nav>
</nav>